name: End-to-End DevSecOps CI/CD (Local KIND)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: hello8989/bankapp
  K8S_CONTEXT: kind-dev-cluster

jobs:

destroy_kind:
    runs-on: self-hosted
    needs: docker_build
    steps:
      - uses: actions/checkout@v4

      - name: Delete to KIND
        run: kubectl delete -f ds.yml

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/bankapp
          kubectl get pods
          kubectl get svc
